[development]
# FLASK
FLASK_DEBUG = false
FLASK_TESTING = false
FLASK_ENV = 'development'
# JWT
JWT_TOKEN_LOCATION = ['headers']
JWT_ACCESS_TOKEN_EXPIRES = 20
JWT_REFRESH_TOKEN_EXPIRES = 1800
JWT_HEADER_NAME = 'Authorization'
JWT_HEADER_TYPE = 'Bearer'
# SQLALCHEMY
SQLALCHEMY_TRACK_MODIFICATIONS = true